### ISSUE TITLE
Difference between GNU Parallel?

### ISSUE THREAD

**Issue by ole-tange** [darkguy2008/parallelshell#33]
Can you explain what the difference is between parallelshell and GNU Parallel? Specifically:

parallel --halt now,fail=1 ::: "echo 1" "echo 2" "echo 3"

**Comment by keithamus** [comment]
Hey @ole-tange thanks for the issue.

The biggest difference is that parallelshell is an npm module and gnu parallel isn't. While they probably do similar things, albeit (gnu) parallel being more advanced, parallelshell is an easier option to work with when using npm (because it's an npm module).

If you have gnu parallel installed on all the machines you project will be on, then by all means use it!

**Comment by anko** [comment]
Perhaps the readme could mention it? For those who know GNU Parallel already, seeing it mentioned in the first paragraph would quickly explain the purpose of this module.

**Comment by mirzazeyrek** [comment]
@anko It's not a nagware I suppose.

**Comment by darkguy2008** [comment]
I added @keithamus explanation to the Readme file so it's clearer. Thanks!
